### ISSUE TITLE
Increasing the maximum file size allowed in isis

### ISSUE THREAD

**Issue by knservis** [nasa-jpl/sstmp#30]
Hi @foobarbecue,

Isis annoyingly does not have an easy way to override the maximum file size conveniently (say through env var). 
My use-case involves very large files so would you consider a PR changing the following to `512` ?
https://github.com/nasa-jpl/sstmp/blob/d0793d26f6dbd6bab3b78206d63916933015255f/src/moon/IsisPreferences#L122

I have worked around this in a second Dockerfile for now, but I would much prefer using this repo if that can be accommodated, and if it does not cause any issues.

**Comment by foobarbecue** [comment]
Yes, let's do that. I'm likely to run into this limit too.
